version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "8001:8001"  # Redis Insight (GUI)
      - "6379:6379"  # Redis port
    networks:
      - middleware-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

  middleware:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: middleware-container
    ports:
      - "8080:8080"  # Spring Boot application port
    depends_on:
      - redis
    networks:
      - middleware-network
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    restart: unless-stopped

networks:
  middleware-network:
    driver: bridge

volumes:
  redis-data:
    driver: local